version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - nielseniq

  db:
    container_name: db
    image: mongo
#    ports:
#      - ":"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - nielseniq

networks:
  nielseniq:
    driver: bridge
