
###

POST http://localhost:8080/add/users
Content-Type: multipart/form-data

< DataNoFriends

###

GET localhost:8080/users/list

###

DELETE localhost:8080/delete/user/1t

###

GET localhost:8080/user/1t

###

PATCH http://localhost:8080/user/1t
Content-Type: application/json

{
  "name": "Nikki Farley Far Away",
  "gender": "female",
  "password": "newpwssssssssd",
  "company": "Ecole 42",
  "email": "nikkifarley@ecole42.com",
  "phone": "+1 (868) 439-2675",
  "address": "588 Schaefer Street, Falconaire, Missouri, 9457",
  "data": "lalalal"
}
